version: '3.8'

services:
  web:
    build: .
    container_name: budget-tracker-app
    ports:
      - "4000:4000"
    env_file:
      - .env
    environment:
      - PORT=4000
    networks:
      - default
